# Generated by Django 3.1.1 on 2020-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telepon',
            field=models.CharField(max_length=13),
        ),
    ]
