# Generated by Django 3.1.1 on 2020-09-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_layanan', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.users')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
