# Generated by Django 3.1.1 on 2020-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='harga',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
