# Generated by Django 3.1.1 on 2020-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_services_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
