# Generated by Django 3.1.1 on 2020-09-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='diskon_persen',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='diskon_rupiah',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
