# Generated by Django 3.1.1 on 2020-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_auto_20200916_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='diskon_persen',
            field=models.IntegerField(),
        ),
    ]
